overrides: .nocover.yaml

name: coala-quickstart
contact: coala.analyzer@gmail.com
description: A quickstart tool for coala
current_version: 0.4.0
version: 0.4.0
build_version: 0.4.0
package_module: coala_quickstart
url: https://github.com/coala/coala-quickstart
docs_dir: false
test_timeout: 60

maintainers: false
maintainer_list:
  - Satwik Kansal
  - Adrian Zatreanu
  - Alexandros Dimos
  - Adhityaa Chandrasekar
maintainer_emails:
  - satwikkansal@gmail.com
  - adrianzatreanu1@gmail.com
  - alexandros.dimos.95@gmail.com
  - c.adhityaa@gmail.com

entry_points:
  console_scripts:
    - coala-quickstart = coala_quickstart.coala_quickstart:main

dependencies:
  - git+https://github.com/coala/coala#egg=coala
  - git+https://github.com/coala/coala-bears#egg=coala-bears
  - gemfileparser~=0.6.2
  - pyjsparser~=2.4.5

configuration:
  template_dir:
    - ../coala-mobans/templates/
    - ../coala-mobans/assets/
  configuration: .moban.yaml
  configuration_dir: ../coala-mobans/
targets:
  - .ci/fix_path.py: ci/fix_path.py
  - .gitignore: coala-gitignore.jj2
  - .editorconfig: .editorconfig.jj2
  - setup.py: coala-setup.py.jj2
  - setup.cfg: setup.cfg.jj2
  - requirements.txt: requirements.txt.jj2
  - test-requirements.txt: test-requirements.txt.jj2
  - coala_quickstart/VERSION: VERSION.jj2
  - coala_quickstart/__init__.py: __init__.py.jj2
  - .ci/appveyor.yml: ci/appveyor.yml.jj2
  - .ci/run_with_env.cmd: run_with_env.cmd
  - .ci/check_moban.sh: ci/check_moban.sh
