overrides: coala.yaml

nocover_file_globs:
  - coala_quickstart/generation/Bears.py
  - coala_quickstart/generation/SettingsFilling.py
  - coala_quickstart/info_extractors/EditorconfigInfoExtractor.py
  - coala_quickstart/info_extractors/EditorconfigParsing.py
  - coala_quickstart/info_extractors/GemfileInfoExtractor.py
  - coala_quickstart/info_extractors/GruntfileInfoExtractor.py

nocover_regexes:
  - nocover
