overrides: coala.yaml

nocover_file_globs:
  - coala_quickstart/generation/Bears.py
  - coala_quickstart/generation/SettingsFilling.py
  - coala_quickstart/info_extractors/EditorconfigInfoExtractor.py
  - coala_quickstart/info_extractors/EditorconfigParsing.py
  - coala_quickstart/info_extractors/GemfileInfoExtractor.py
  - coala_quickstart/info_extractors/GruntfileInfoExtractor.py
  - coala_quickstart/generation/Utilities.py

nocover_regexes:
  - nocover
  - args.green_mode
  - def language_percentage
  - INFO_SETTING_MAPS =
  - gitignore_dir_list
  - if ignore_globs is None
  # coala_quickstart/generation/Settings.py write_coafile
  - if os.path.isfile(coafile)
  # coala_quickstart/generation/SettingsClass.py fillup_optional_settings
  - if inside_annot
  # ... BearSettings.__init__
  - if hasattr.bear, .generate_config..
