overrides: coala.yaml

allow_generic_no_cover: true

nocover_file_globs:
  - coala_quickstart/generation/Bears.py
  # coala_quickstart/generation/SettingsFilling.py
  - coala_quickstart/info_extractors/EditorconfigInfoExtractor.py
  - coala_quickstart/info_extractors/EditorconfigParsing.py
  - coala_quickstart/info_extractors/GemfileInfoExtractor.py
  - coala_quickstart/info_extractors/GruntfileInfoExtractor.py
  # coala_quickstart/generation/Utilities.py

nocover_regexes:
  - nocover
  - args.green_mode
  - def language_percentage
  - INFO_SETTING_MAPS =
  - gitignore_dir_list
  - 'if ignore_globs is None:'
  # coala_quickstart/generation/Settings.py write_coafile
  - 'if os.path.isfile\(coafile\):'
  #    generation/SettingsFilling
  - def autofill_value
  - def is_autofill_possible
  - def require_setting
  # .. generation/Utilities.py
  - def is_glob_exp
  - def parse_gitignore_line
  - def get_language_from_hashbang
  # get_extensions
  - if ext in exts
  # coala_quickstart/generation/SettingsClass.py fillup_optional_settings
  - if inside_annot
  # ... BearSettings.__init__
  - if hasattr.bear, .generate_config..
