language: python
python:
  - 3.4
  - 3.5
  - 3.6

cache:
  pip: true

before_install:
  - pip install setuptools -U
  - pip install -r requirements.txt -r test-requirements.txt

script:
  - pytest
  - pip install -e .
  # https://github.com/coala/coala-bears/issues/1037
  - >
    if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
      sed -i.bak '/bears = GitCommitBear/d' .coafile
    fi
  - coala --non-interactive

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never

branches:
  exclude:
    - /^sils\//
