image: Visual Studio 2015

environment:
  global:
    PIP_CACHE_DIR: C:\pip_cache
    # Needed if pip uninstall is used
    PIP_YES: 1
    NUGET_EXE_NO_PROMPT: 1
    NUGET_HTTP_CACHE_PATH: C:\nuget_http_cache
    CHOCO_CACHE_DIR: C:\choco_cache
    PLATFORM: $(PLATFORM)
    MSYS_ROOT: C:\msys64
    MSYS_BIN: $(MSYS_ROOT)\usr\bin
    MINGW_BIN: C:\MinGW\bin
    WIN71_SDK_ROOT: C:\Program Files\Microsoft SDKs\Windows\v7.1
    VS14_VC: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    VS2017: C:\Program Files (x86)\Microsoft Visual Studio\2017
    VS2017_VC: $(VS2017)\Community\VC
    PATH: >-
      C:\python;C:\python\Scripts;$(PATH);$(MINGW_BIN);$(MSYS_BIN);
      %USERPROFILE%\.nuget\packages\fudge\1.3.0\tools;

  matrix:
    - PYTHON_VERSION: 3.5.4
      PYTHON_MINOR_NODOTS: 35

    - PYTHON_VERSION: 3.4.4
      PYTHON_MINOR_NODOTS: 34

    - PYTHON_VERSION: 3.6.8
      PYTHON_MINOR_NODOTS: 36

platform:
  - x64
  - x86

cache:
  - C:\nuget_http_cache
  - C:\choco_cache
  - "C:\\pip_cache"
  - "C:\\Users\\appveyor\\AppData\\Roaming\\nltk_data"

branches:
  except:
    - /^sils\/.*/

install:
  # Show initial state
  - python --version
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Stores environment in registry, with minor tweaks
  - python .ci/fix_path.py
  - refreshenv

  - mv C:\python%PYTHON_MINOR_NODOTS% C:\python
  - python --version
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  - "%MSYS_BIN%\\date.exe"
  # Install lxml needed by for coala-bears as a wheel as libxml2 and libxslt
  # headers and library files are not available, and STATIC_DEPS=true often
  # results in linter problems due to different VS compilers and MS runtimes.
  - python -m pip install --prefer-binary lxml
  - python -m pip install -U six pip==9.0.3 setuptools==21.2.2

  # Install dependencies
  - python -m pip install
      --constraint requirements.txt
      git+https://gitlab.com/coala/PyPrint#egg=PyPrint

  - python -m pip install
      --constraint requirements.txt
      git+https://gitlab.com/coala/coala-utils#egg=coala-utils

  - python -m pip install
      --constraint requirements.txt
      git+https://github.com/coala/coala#egg=coala

  - python -m pip install
      --constraint requirements.txt
      git+https://github.com/coala/coala-bears#egg=coala-bears

  - python -m pip install
      --constraint requirements.txt
      -r requirements.txt

  - python -m pip install
      --constraint requirements.txt
      pip==9.0.3 setuptools==21.2.2
      -e .

  - python -m pip install
      --constraint requirements.txt
      -r test-requirements.txt


  - "%MSYS_BIN%\\date.exe"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - py.test
  - python setup.py install
  - python -m pip install
      git+https://github.com/coala/coala#egg=coala
      git+https://github.com/coala/coala-bears#egg=coala-bears

  - rm -f MYMETA.yml
  - sed -i '/ShellCheckBear/d' .coafile
  - coala --ci

on_success:
  - codecov

on_failure:
  - codecov

matrix:
  fast_finish: true
